version: "3.9"
services:
  runner:
    build: .
    env_file: .env
    environment:
      - LABELS=${LABELS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 2
