name: deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: EPFL-ENAC/epfl-enac-deploy-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
