name: deploy

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker run --rm -v $(pwd)/root/.ssh:/tmp/.ssh:ro -v $(pwd)/root/.enacit-ansible_vault_password:/root/.enacit-ansible_vault_password:ro ghcr.io/epfl-enac/ansible:latest ansible-playbook -i inventory/enacvm0127.xaas.epfl.ch.yml playbooks/app-deploy.yml
